# Generated by Django 5.2.3 on 2025-11-07 00:19

from django.db import migrations

REQUIRED_GROUPS = [
    "Admins",
    "Moderators",
    "Developers"
]



def create_required_groups(apps, schema_editor):
    """
    Creates the required groups in the database.
    We use apps.get_model to get the historical version of the Group model.
    """
    Group = apps.get_model('auth', 'Group')
    for group_name in REQUIRED_GROUPS:
        # get_or_create returns a tuple of (object, created_boolean)
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f'Created group: {group_name}')
        else:
            print(f'Group "{group_name}" already exists.')

def remove_required_groups(apps, schema_editor):
    """
    This function is optional, but good practice.
    It allows the migration to be reversed.
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=REQUIRED_GROUPS).delete()
    print(f'Deleted groups: {", ".join(REQUIRED_GROUPS)}')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_avatar_url_remove_user_discord_id_and_more'),
    ]

    operations = [
        migrations.RunPython(create_required_groups, reverse_code=remove_required_groups),
    ]
